lint:
  files_exist:
    - .github/workflows/ci.yml
  files_unchanged:
    - .gitignore
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Friederike Hanssen, Susanne Jodoin
  description: Workflow converts one or multiple bam/cram files to fastq format
  force: false
  is_nfcore: true
  name: bamtofastq
  org: nf-core
  outdir: .
  version: 2.2.0
